print("jack and jill went up the hill")
print("to fetch a pail of water")
print("jack fell down and broke his crown")
print("and jill came tumbling after")
print("-"*20)
print("python can do math too")
print("2+2 is",2+2)
print("3*4 is",3*4)
print("100-1 is",100-1)
print("(33+2)/5+11.5 is",(33+2)/5+11.5)
#comments go here
